name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kaocha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: kaocha
        with:
          path: |
            ~/.gitlibs
            ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.739"
      - run: bin/kaocha
      - uses: codecov/codecov-action@v1.0.15

  cljstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: cljstyle
        with:
          path: |
            ~/.gitlibs
            ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.739"
      - run: bin/cljstyle check --report

  clj-kondo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: clj-kondo
        with:
          path: |
            ~/.gitlibs
            ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.739"
      - run: bin/clj-kondo --lint .

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: check
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
            ~/.gitlibs
            ~/.m2
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: DeLaGuardo/setup-clojure@3.0
        with:
          cli: "1.10.1.739"
      - run: bin/check

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env:
          cache-name: prettier
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: prettier --all-files
