name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Clojure
      uses: DeLaGuardo/setup-clojure@3.0
      with:
        cli: "1.10.1.739"
    - name: run tests
      run: bin/kaocha
      env:
        CI: "1"
